### ISSUE TITLE
Debug invalid date

### ISSUE THREAD

**Issue by Keyrxng** [ubiquibot/automated-merging#8]
See [this run](https://github.com/ubiquibot/automated-merging/actions/runs/10364946064/job/28691136589) and about 6 log sets down you see 

![image](https://github.com/user-attachments/assets/e691a59d-baff-4dd6-9650-ea958eaf5ad6)

Which is linking to this [pull request](https://github.com/ubiquibot/conversation-rewards/pull/79) and is the only invalid date string in the logs (I only checked this run and it was for an unrelated matter)

**Comment by gentlementlegen** [comment]
@Keyrxng Thank you for noticing this. We should try again after https://github.com/ubiquibot/automated-merging/pull/4 is merged because maybe it is fixed by the fact we do not use the database anymore and because it will exclude pull-requests that are still on draft mode (I do not know if the invalid date is related to these).

**Comment by gentlementlegen** [comment]
I think since we removed the DB everything runs as expected, cf run https://github.com/ubiquibot/automated-merging/actions/runs/10503328822/job/29096477913, can close this.
